import os
import re
from openai import OpenAI
from dotenv import load_dotenv

# Load FANAR API key
load_dotenv(".env")

# Initialize FANAR client
client = OpenAI(
    base_url="https://api.fanar.qa/v1",
    api_key=os.getenv("FANAR_API_KEY"),
)

def full_read(paper: str, llm_prompt_path: str) -> str:
    """
    Summarises a research paper into structured bullet points using the ChatHPaper prompt template.

    Args:
        paper (str): The Markdown content of the paper.
        llm_prompt_path (str): Path to the prompt text file for ChatHPaper (the instruction template).

    Returns:
        str: The bullet-point structured summary generated by the LLM.
    """

    # Load the prompt template
    try:
        with open(llm_prompt_path, "r", encoding="utf-8") as f:
            llm_prompt = f.read().strip()
    except FileNotFoundError:
        raise ValueError(f"Prompt file not found at: {llm_prompt_path}")

    # Combine prompt with paper content
    full_prompt = f"{llm_prompt}\n\n---\n\n{paper}"

    # Send to FANAR LLM
    response = client.chat.completions.create(
        model="Fanar",
        messages=[
            {"role": "system", "content": "You are a research assistant that extracts structured academic data."},
            {"role": "user", "content": full_prompt},
        ],
        temperature=0,  # keep factual and structured
    )

    # Extract and return the model output text
    return response.choices[0].message.content.strip()

def clean_paper_md(md):

    # Remove References 
    md = re.sub(r'(?i)^#\s*References\b.*?(?=^#|\Z)', '', md, flags=re.DOTALL | re.MULTILINE).strip()

    # Remove Markdown links like [something](#page-4-0)
    md = re.sub(r'\[.*?\]\(.*?page.*?\)', '', md).strip()
    
    # Remove HTML tags like <span> or </span>
    md = re.sub(r'<.*?>', '', md).strip()

    # Remove heading tag # 
    md = md.replace("#", "").strip()

    return md

paper_path = r"data\markdown_papers\A Simple Transformer-Based Model for Ego4D Natural Language Queries Challenge.md"
with open(paper_path, "r", encoding="utf-8") as f:
    paper_content = f.read()


paper_content = clean_paper_md(paper_content)
result = full_read(paper_content, r"full_screening\inclusion_prompt.txt")

print(result)

'''
- Task relevant (video retrieval / QA / semantic search): YES
- Uses CV (detection, action recognition, scene understanding): YES
- Uses Audio/ASR: NO
- Uses NLP/LLM: YES
- Multimodal fusion (vision+audio+text): YES
- Has experiment on real video data: YES
- Supports natural-language/semantic queries (query-by-meaning): YES
- Mentions retrieval metrics (Recall@K, mAP, R@1, etc.): YES
- Authors: Sicheng Mo, Fangzhou Mu, Yin Li
- Affiliation: University of Wisconsin-Madison
- Journal or Conference: -
- Keywords: Transformers, Temporal Action Localization, Video Grounding, Natural Language Queries, Ego4D Dataset
- Datasets: Ego4D Dataset
- Application: Video Search using Natural Language Queries
- Related works: Prior work on temporal action localization, existing video grounding methods, especially mentioning ActionFormer and CLIP. Also mentions competing submissions like ReLER@ZJU-Alibaba.
- Experiments: Experimentation with different video features (SlowFast, Omnivore, EgoVLP). Ensembling of these features. Training and validation on provided splits. Testing on private test set.
- Results: Achieved 12.64% Mean R@1 and 28.45% R@5 @tIoU=0.3 on the test set. Outperforms baseline methods and ranks second on the leaderboard. Highlighted strengths in R@5 metric.
- Limitations: Sticks to moments where objects are present rather than deducing answers from context. Higher R@5 suggests potential improvements through stronger classification heads.
- Repository: Not explicitly stated in the paper but likely linked to UW Madison researchers' repositories or GitHub pages.
- Recommendations: Explicitly reason about text queries to avoid sticking to presence of objects. Improve classification heads for better performance. Investigate integration of audio features for broader applications. Continue exploring lightweight transformer architectures for faster inference times.
- Notes: Minimalistic design leveraging ActionFormer for video grounding. Strong performance despite simplicity. Explores various video features and ensembles them effectively. Focuses on natural language queries in egocentric videos.
- Reason of relevance: Highly relevant due to direct addressing of semantic video retrieval using multimodal embeddings and natural language queries, meeting all defined inclusion criteria except for specific mention of "action recognition" being general "scene understanding". However, given the nature of the task focusing on localized events described by natural language queries, it fits perfectly within the scope of "Task relevant (video retrieval / QA / semantic search)".
'''